server:
  port: 8001
spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      server-addr: 101.34.205.164:8848
    gateway:
      routes:
        - id: product-router
          uri: lb://gmall-product
          predicates:
          - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}