spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.205.164:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: gmall-product
  cloud:
    nacos:
      server-addr: 101.34.205.164:8848
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: showStatus
      logic-delete-value: 1
      logic-not-delete-value: 0

mybatis-plus:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml